import  { LevelProvider } from "./Context/LevelContext";
import { NameProvider } from "@/app/Context/NameContext"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icon: '/favicon.ico' ,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head/>
      <body>
        <NameProvider>
        <LevelProvider>
        {children}
        </LevelProvider>
        </NameProvider>
        </body>
    </html>
  )
}
