export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icon: '/favicon.ico' ,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head/>
      <body>{children}</body>
    </html>
  )
}
